apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3-8B"
            - "--max-model-len=4096"
            - "--enable-chunked-prefill"
            - "--tensor-parallel-size=1"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
          resources:
            limits:
              cpu: "16"
              memory: 32Gi
              nvidia.com/gpu: 1
            requests:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
